from os import system

system("python -m black main")
system("python -m black main/test")
system("python -m black main/src")
system("python -m black main/src/factory")
system("python -m black main/src/flyweights")
system("python -m black main/src/gui")
system("python -m black main/src/object")
system("python -m black main/src/observers")
system("python -m black main/src/prototypes")
system("python -m black main/src/states")
system("python -m black main/src/utils")
system("python -m black main/src/gui/menu_items")
system("python -m black main/src/gui/ui")
system("python -m black main/src/object/enemies")
system("python -m black main/src/object/players")
system("python -m black main/src/object/support_items")
system("python -m black main/src/object/weapons")
print("Done")